apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team62-users-api
        name: users-api
        ports:
        - containerPort: 8083
          name: usersport
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-api
              key: JWT_SECRET
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: users-api
              key: SERVER_PORT
        # livenessProbe:
        #   tcpSocket:
        #     port: usersport
        #   failureThreshold: 3
        #   initialDelaySeconds: 30
        #   periodSeconds: 15
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # readinessProbe:
        #   tcpSocket:
        #     port: usersport
        #   failureThreshold: 3
        #   initialDelaySeconds: 1
        #   periodSeconds: 15
        #   successThreshold: 1
        #   timeoutSeconds: 2
      restartPolicy: Always
