apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: 561341012850.dkr.ecr.us-east-1.amazonaws.com/team62-frontend
        name: frontend
        ports:
        - containerPort: 8080
          name: fport
        env:
        - name: AUTH_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: AUTH_API_ADDRESS
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: PORT
        - name: TODOS_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: frontend
              key: TODOS_API_ADDRESS
        
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: fport
        #   failureThreshold: 3
        #   initialDelaySeconds: 30
        #   periodSeconds: 15
        #   successThreshold: 1
        #   timeoutSeconds: 2
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: fport
        #   failureThreshold: 3
        #   initialDelaySeconds: 1
        #   periodSeconds: 15
        #   successThreshold: 1
        #   timeoutSeconds: 2
      restartPolicy: Always
